repository: iNDS-Team/iNDS
logo: /Resources/required/AppIcon256.png
screenshot: /Resources/IMG_0005.jpg
cydia_repo: https://inds.nerd.net
google_analytics: UA-118954430-1

# Build settings
markdown: GFM
remote_theme: iNDS-Team/iNDS-Theme
plugins:
  - jekyll-remote-theme
  - jekyll-optional-front-matter
favicon: Resources/favicon.ico

sass:
  style: compact

include:
  - CONTRIBUTING.md
  - CODE_OF_CONDUCT.md

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - iNDS
  - desmume
  - build
  - Images.xcassets
  - Tools
  - gendeb.sh
  - genipa.sh
  - gensite.sh
  - Makefile
  - Podfile
  - Podfile.lock
  - Pods

